package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema      string `json:"api_schema"`
	MaterialCode   string `json:"material_code"`
	Plant_Supplier string `json:"plant/supplier"`
	Stock          string `json:"stock"`
	DocumentType   string `json:"document_type"`
	DocumentNo     string `json:"document_no"`
	PlannedDate    string `json:"planned_date"`
	ValidatedDate  string `json:"validated_date"`
	Deleted        bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey   string `json:"connection_key"`
	Result          bool   `json:"result"`
	RedisKey        string `json:"redis_key"`
	Filepath        string `json:"filepath"`
	RouteCollection struct {
		ObjectID                    string `json:"ObjectID"`
		ETag                        string `json:"ETag"`
		ID                          string `json:"ID"`
		Name                        string `json:"Name"`
		RouteTypeCode               string `json:"RouteTypeCode"`
		RouteTypeCodeText           string `json:"RouteTypeCodeText"`
		StartDate                   string `json:"StartDate"`
		ExcludeMondayIndicator      bool   `json:"ExcludeMondayIndicator"`
		ExcludeTuesdayIndicator     bool   `json:"ExcludeTuesdayIndicator"`
		ExcludeWednesdayIndicator   bool   `json:"ExcludeWednesdayIndicator"`
		ExcludeThursdayIndicator    bool   `json:"ExcludeThursdayIndicator"`
		ExcludeFridayIndicator      bool   `json:"ExcludeFridayIndicator"`
		ExcludeSaturdayIndicator    bool   `json:"ExcludeSaturdayIndicator"`
		ExcludeSundayIndicator      bool   `json:"ExcludeSundayIndicator"`
		SalesTerritoryID            string `json:"SalesTerritoryID"`
		SalesOrganisationID         string `json:"SalesOrganisationID"`
		OrganizerPartyID            string `json:"OrganizerPartyID"`
		DefaultStartTime            string `json:"DefaultStartTime"`
		DefaultPreparationTime      string `json:"DefaultPreparationTime"`
		DefaultDuration             string `json:"DefaultDuration"`
		VisitTypeCode               string `json:"VisitTypeCode"`
		VisitTypeCodeText           string `json:"VisitTypeCodeText"`
		Status                      string `json:"Status"`
		StatusText                  string `json:"StatusText"`
		ProcessingStatus            string `json:"ProcessingStatus"`
		ProcessingStatusText        string `json:"ProcessingStatusText"`
		OwnerPartyID                string `json:"OwnerPartyID"`
		OwnerPartyUUID              string `json:"OwnerPartyUUID"`
		PerfectStoreIndicator       bool   `json:"PerfectStoreIndicator"`
		DistributionChannelCode     string `json:"DistributionChannelCode"`
		DistributionChannelCodeText string `json:"DistributionChannelCodeText"`
		DivisionCode                string `json:"DivisionCode"`
		DivisionCodeText            string `json:"DivisionCodeText"`
		AutomaticResequencing       bool   `json:"AutomaticResequencing"`
		EndDate                     string `json:"EndDate"`
		WorkingDayCalendarCode      string `json:"WorkingDayCalendarCode"`
		WorkingDayCalendarCodeText  string `json:"WorkingDayCalendarCodeText"`
		RouteAccountCollection      struct {
			ObjectID                       string `json:"ObjectID"`
			ParentObjectID                 string `json:"ParentObjectID"`
			ETag                           string `json:"ETag"`
			RouteID                        string `json:"RouteID"`
			AccountID                      string `json:"AccountID"`
			AccountUUID                    string `json:"AccountUUID"`
			AllDayEvent                    bool   `json:"AllDayEvent"`
			DayNumber                      int    `json:"DayNumber"`
			DriveTime                      string `json:"DriveTime"`
			Duration                       string `json:"Duration"`
			EndTime                        string `json:"EndTime"`
			StartTime                      string `json:"StartTime"`
			PreparationTime                string `json:"PreparationTime"`
			VisitDate                      string `json:"VisitDate"`
			VisitTypeCode                  string `json:"VisitTypeCode"`
			VisitTypeCodeText              string `json:"VisitTypeCodeText"`
			VisitUUID                      string `json:"VisitUUID"`
			VisitID                        string `json:"VisitID"`
			RouteInvolvedPartiesCollection struct {
				ObjectID                        string `json:"ObjectID"`
				ParentObjectID                  string `json:"ParentObjectID"`
				ETag                            string `json:"ETag"`
				RouteID                         string `json:"RouteID"`
				PartyID                         string `json:"PartyID"`
				PartyName                       string `json:"PartyName"`
				RoleCode                        string `json:"RoleCode"`
				RoleCodeText                    string `json:"RoleCodeText"`
				RoleCategoryCode                string `json:"RoleCategoryCode"`
				RoleCategoryCodeText            string `json:"RoleCategoryCodeText"`
				PartyTypeCode                   string `json:"PartyTypeCode"`
				PartyTypeCodeText               string `json:"PartyTypeCodeText"`
				Address                         string `json:"Address"`
				Email                           string `json:"Email"`
				FormattedPhoneNumberDescription string `json:"FormattedPhoneNumberDescription"`
				Route                           string `json:"Route"`
			} `json:"RouteInvolvedPartiesCollection"`
		} `json:"RouteAccountCollection"`
	} `json:"RouteCollection"`
	APISchema string   `json:"api_schema"`
	Accepter  []string `json:"accepter"`
	RouteCode string   `json:"route_code"`
	Deleted   bool     `json:"deleted"`
}
